__title__ = 'exrates'
__description__ = 'Simple exchange rates'
__url__ = 'http://github'
__version__ = '1.0'
__author__ = 'Ömer GÖK'
__author_email__ = 'omergok@outlook.com'
__license__ = 'MIT'
__copyright__ = 'Copyright 2019 Ömer GÖK'